# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specification', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('inventory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_items.Inventory')),
            ],
            options={
                'db_table': 'tbl_inventory_item_list',
            },
        ),
    ]
