# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tbl_all_users',
        ),
    ]
