# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_items', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_email_activated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_all_users',
            },
        ),
    ]
