# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_items', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventoryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('is_pending', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='inventoryitemlist',
            name='defected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinventorymapping',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_items.InventoryItemList'),
        ),
        migrations.AddField(
            model_name='userinventorymapping',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
